In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
stocks = pd.read_csv('C:\\Users\\aiden\\dev\\kaggle\\python\\stock_details_5_years.csv')
stocks.shape

(602962, 9)

In [3]:
stocks.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company
0,2018-11-29 00:00:00-05:00,43.829761,43.863354,42.639594,43.083508,167080000,0.00,0.0,AAPL
1,2018-11-29 00:00:00-05:00,104.769074,105.519257,103.534595,104.636131,28123200,0.00,0.0,MSFT
2,2018-11-29 00:00:00-05:00,54.176498,55.007500,54.099998,54.729000,31004000,0.00,0.0,GOOGL
3,2018-11-29 00:00:00-05:00,83.749496,84.499496,82.616501,83.678497,132264000,0.00,0.0,AMZN
4,2018-11-29 00:00:00-05:00,39.692784,40.064904,38.735195,39.037853,54917200,0.04,0.0,NVDA

In [4]:
stocks.isna().sum()
stocks.isnull().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
Company         0
dtype: int64

In [5]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 602962 entries, 0 to 602961
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          602962 non-null  object
 1   Open          602962 non-null  float64
 2   High          602962 non-null  float64
 3   Low           602962 non-null  float64
 4   Close         602962 non-null  float64
 5   Volume        602962 non-null  int64
 6   Dividends     602962 non-null  float64
 7   Stock Splits  602962 non-null  float64
 8   Company       602962 non-null  object
dtypes: float64(6), int64(1), object(2)
memory usage: 41.4+ MB

In [6]:
stocks.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,602962.000000,602962.000000,602962.000000,602962.000000,6.029620e+05,602962.00000,602962.000000
mean,140.074711,141.853492,138.276316,140.095204,5.895601e+06,0.00731,0.000344
std,275.401725,279.003191,271.895276,275.477969,1.381596e+07,0.12057,0.050607
min,1.052425,1.061195,1.026114,1.034884,0.000000e+00,0.00000,0.000000
25%,39.566159,40.056222,39.058151,39.563746,1.031500e+06,0.00000,0.000000
50%,79.177964,80.125563,78.193820,79.177906,2.228700e+06,0.00000,0.000000
75%,157.837190,159.746317,155.841609,157.847153,5.277400e+06,0.00000,0.000000
max,6490.259766,6525.000000,6405.000000,6509.350098,1.123003e+09,35.00000,20.000000

In [7]:
stocks['Date'] = pd.to_datetime(stocks['Date'], utc=True)
stocks.set_index('Date', inplace=True)

In [8]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 602962 entries, 2018-11-29 05:00:00+00:00 to 2023-11-29 05:00:00+00:00
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Open          602962 non-null  float64
 1   High          602962 non-null  float64
 2   Low           602962 non-null  float64
 3   Close         602962 non-null  float64
 4   Volume        602962 non-null  int64
 5   Dividends     602962 non-null  float64
 6   Stock Splits  602962 non-null  float64
 7   Company       602962 non-null  object
dtypes: float64(6), int64(1), object(1)
memory usage: 41.4+ MB

In [9]:
stocks['Volume'] = stocks['Volume'].astype('float64')
stocks['Company'] = stocks['Company'].astype('category')

In [10]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 602962 entries, 2018-11-29 05:00:00+00:00 to 2023-11-29 05:00:00+00:00
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Open          602962 non-null  float64
 1   High          602962 non-null  float64
 2   Low           602962 non-null  float64
 3   Close         602962 non-null  float64
 4   Volume        602962 non-null  float64
 5   Dividends     602962 non-null  float64
 6   Stock Splits  602962 non-null  float64
 7   Company       602962 non-null  category
dtypes: category(1), float64(7)
memory usage: 38.0 MB

In [11]:
stocks.nunique()

Open            510592
High            514315
Low             513389
Close           484353
Volume          170929
Dividends          960
Stock Splits        40
Company            491
dtype: int64

In [12]:
stocks['Close'].value_counts()

Close
2.910000       32
3.140000       30
9.950000       28
3.130000       27
10.000000      26
               ..
184.710007      1
15.855000       1
197.583298      1
6139.129883     1
134.436371      1
Name: count, Length: 484353, dtype: int64

In [ ]:
plt.figure(figsize=(8, 6))
plt.bar(stocks['Company'], stocks['Close'], color='deeppink')
plt.title('Count Plot of Close Prices by Company', fontsize=16)
plt.xlabel('Company', fontsize=16)
plt.ylabel('Count')
plt.show()

KeyboardInterrupt: